name: {{SERVICE_NAME}}-production
services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${APP_PORT}
    ports:
      - "127.0.0.1:${APP_PORT}:${APP_PORT}"
